---
- hosts: localhost
  vars:
    state: present
    s3_bucket: eapenmani-kottayam
    key: terraform-jenkins.tfstate
    region: us-east-1
    app_env: dev
  tasks:
    - name: Run terraform scripts
      terraform:
        project_path: "./"  
        state: "{{ state }}"
        backend_config:
          bucket: "{{s3_bucket}}"
          key: "{{key}}"
          region: "{{region}}"
        variables_file: "{{app_env}}.tfvars"  
        workspace: "{{app_env}}"